//! The OKF vocabulary the canonical unit speaks (ADR-140 D4, as amended
//! 2026-09-22 by ADR-141).
//!
//! ADR-140 minted its own names for the two content families \[Evo\] measured as
//! load-bearing: `Mapping` (bind a term to a queryable locus) and `Evidence` (a
//! probe that was executed and its result digested). The Open Knowledge Format
//! v0.2 already names both, and the sovereign-corpus build validates against
//! that vocabulary, so Loom adopts OKF's spelling rather than carrying a
//! private synonym for a public term:
//!
//! | ADR-140 name | OKF name here |
//! |---|---|
//! | `Evidence` | [`AttestedComputation`] — a computation, its executor and its attester |
//! | `Mapping.iri` | [`Mapping::resource`] — the OKF `resource` URI |
//! | `CorpusNature` | [`Provenance`] — `generated` by whom, `verified` by whom |
//!
//! The substance is unchanged: an attested computation is still "a probe that
//! ran and whose result a named party stands behind". What changes is that the
//! claim is now expressed in the same terms as the corpus that carries it, and
//! that trust is per-entry rather than a single corpus-wide honesty label.
//!
//! Nothing here is runtime state. These are corpus content under the same
//! governance as the prose they accompany.

use std::collections::BTreeMap;

/// An OKF actor URI: `human:<npub>`, `process:<name>/<version>` or
/// `agent:<producer>/<version>`.
///
/// A newtype rather than a `String` because the trust tier a
/// [`CoverageReport`](crate::manifest::CoverageReport) counts is read off the
/// prefix, and a bare string would let a caller count a process as a human.
#[derive(
    Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
pub struct Actor(String);

impl Actor {
    /// Wrap an actor URI verbatim.
    #[must_use]
    pub fn new(uri: impl Into<String>) -> Self {
        Self(uri.into())
    }

    /// `human:<npub>` — the signer tier the governance loop requires for a
    /// Content or Schema change.
    #[must_use]
    pub fn human(npub: &str) -> Self {
        Self(format!("human:{npub}"))
    }

    /// `process:<name>/<version>` — a deterministic build step.
    #[must_use]
    pub fn process(name: &str, version: &str) -> Self {
        Self(format!("process:{name}/{version}"))
    }

    /// `agent:<producer>/<version>` — a model-driven producer.
    #[must_use]
    pub fn agent(producer: &str, version: &str) -> Self {
        Self(format!("agent:{producer}/{version}"))
    }

    /// The URI as written.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Whether this actor is a human signer.
    #[must_use]
    pub fn is_human(&self) -> bool {
        self.0.starts_with("human:")
    }

    /// Whether this actor is a machine — a build process or an agent. The
    /// complement of [`Self::is_human`] over the OKF actor grammar, stated
    /// positively so an unrecognised prefix counts as neither rather than
    /// silently as a machine.
    #[must_use]
    pub fn is_machine(&self) -> bool {
        self.0.starts_with("process:") || self.0.starts_with("agent:")
    }
}

/// One OKF trust statement: an actor, and when they made it.
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Attestation {
    /// The actor who generated or verified the entry.
    pub by: Actor,
    /// When, RFC 3339. Optional because the corpus predates the field and a
    /// missing timestamp is not a reason to discard the attestation.
    #[serde(default)]
    pub at: Option<String>,
}

impl Attestation {
    /// An attestation with no recorded time.
    #[must_use]
    pub fn by(actor: Actor) -> Self {
        Self {
            by: actor,
            at: None,
        }
    }

    /// An attestation stamped at `at` (RFC 3339).
    #[must_use]
    pub fn at(actor: Actor, at: impl Into<String>) -> Self {
        Self {
            by: actor,
            at: Some(at.into()),
        }
    }
}

/// OKF trust for one canonical unit: who produced it, and who has since
/// verified it.
///
/// The two tiers are deliberately not collapsed into a score. "Generated by the
/// build and verified by nobody" and "generated by the build and verified by a
/// named human" are different claims, and a consumer that cannot distinguish
/// them cannot honour the governance ADR-135 bought.
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Provenance {
    /// Who produced this unit.
    pub generated: Attestation,
    /// Every verification since, in the order the corpus records them. Empty is
    /// the honest common case.
    #[serde(default)]
    pub verified: Vec<Attestation>,
}

impl Provenance {
    /// The default for a unit the build produced and nobody has verified —
    /// `generated: process:vault`, `verified: []`.
    ///
    /// This is what a corpus entry without OKF trust keys resolves to. It is a
    /// weaker claim than the `corpusNature` label it replaces, and deliberately
    /// so: the old label asserted human direction for every unit uniformly,
    /// which was never checkable per entry.
    #[must_use]
    pub fn vault_generated() -> Self {
        Self {
            generated: Attestation::by(Actor::new("process:vault")),
            verified: Vec::new(),
        }
    }

    /// Whether a human has verified this unit.
    #[must_use]
    pub fn is_human_verified(&self) -> bool {
        self.verified.iter().any(|a| a.by.is_human())
    }

    /// Whether a machine — build process or agent — has verified this unit.
    #[must_use]
    pub fn is_machine_verified(&self) -> bool {
        self.verified.iter().any(|a| a.by.is_machine())
    }
}

impl Default for Provenance {
    fn default() -> Self {
        Self::vault_generated()
    }
}

/// Where a term can be *checked*: the queryable locus a [`Mapping`] binds it to
/// (ADR-140 D4). The variant IS the capability claim — a term bound to
/// [`Locus::Sparql`] can be entailment-checked; one bound to [`Locus::Corpus`]
/// can only be read back.
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum Locus {
    /// A pattern over the Whelk-reasoned closure.
    Sparql { pattern: String },
    /// A RuVector namespace, optionally filtered.
    Vector {
        namespace: String,
        #[serde(default)]
        filter: Option<String>,
    },
    /// A vault page — the build's own join key.
    Corpus { page: String },
    /// An external system registered in the PRD-025 connector manifest.
    Connector { source_id: String, selector: String },
}

/// Binds an OKF `resource` to a queryable locus (ADR-140 D4).
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Mapping {
    /// The OKF `resource` URI this mapping binds — `urn:ngm:class:<slug>` for a
    /// class in this corpus. It is the address; there is no second `iri` field,
    /// because OKF already names one.
    pub resource: String,
    /// What can be queried to check the resource.
    pub locus: Locus,
    /// Why this locus, when the binding is a judgement rather than a derivation.
    #[serde(default)]
    pub note: Option<String>,
}

/// Who ran a computation, and what receipt they hold for having run it.
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Executor {
    /// The OKF `resource` URI of the executor (an [`Actor`] URI in practice).
    pub resource: String,
    /// The execution receipt — a run id, a job URN, a log digest. `None` when
    /// the executor kept no receipt, which is worth seeing rather than faking.
    #[serde(default)]
    pub receipt: Option<String>,
}

/// Who stands behind the computation's result.
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Attester {
    /// The OKF `resource` URI of the attester.
    pub resource: String,
}

/// An executed, re-executable computation and the parties behind it — OKF's
/// name for what ADR-140 D4 called `Evidence`.
///
/// Attaching the executor and the attester separately is the point: a build
/// process can *execute* a probe, but only a named party can *attest* that its
/// result means what the corpus says it means.
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct AttestedComputation {
    /// The runtime the computation ran under, e.g. `oxigraph/0.4`.
    pub runtime: String,
    /// Named parameters the computation was given. A sorted map so the record
    /// digests deterministically.
    #[serde(default)]
    pub parameters: BTreeMap<String, String>,
    /// The computation itself — the SPARQL text, the probe expression, the
    /// command. Re-executable by construction.
    pub computation: String,
    /// Who ran it.
    pub executor: Executor,
    /// Who stands behind the result.
    pub attester: Attester,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn actor_tiers_are_read_from_the_okf_prefix() {
        assert!(Actor::human("npub1abc").is_human());
        assert!(!Actor::human("npub1abc").is_machine());
        assert!(Actor::process("vault", "1.0").is_machine());
        assert!(Actor::agent("claude", "opus-5").is_machine());
        // An unrecognised prefix is neither tier, not silently a machine.
        let odd = Actor::new("mystery:someone");
        assert!(!odd.is_human() && !odd.is_machine());
    }

    #[test]
    fn default_provenance_is_vault_generated_and_unverified() {
        let p = Provenance::default();
        assert_eq!(p.generated.by.as_str(), "process:vault");
        assert!(p.verified.is_empty());
        assert!(!p.is_human_verified() && !p.is_machine_verified());
    }

    #[test]
    fn human_and_machine_verification_are_distinguishable() {
        let p = Provenance {
            generated: Attestation::by(Actor::process("vault", "1.0")),
            verified: vec![Attestation::at(
                Actor::human("npub1abc"),
                "2026-09-22T00:00:00Z",
            )],
        };
        assert!(p.is_human_verified());
        assert!(!p.is_machine_verified());
    }

    #[test]
    fn locus_round_trips_as_a_tagged_object() {
        let locus = Locus::Vector {
            namespace: "ontology-corpus".to_owned(),
            filter: None,
        };
        let json = serde_json::to_string(&locus).expect("serialise");
        assert!(json.contains("\"kind\":\"vector\""), "{json}");
        let back: Locus = serde_json::from_str(&json).expect("deserialise");
        assert_eq!(back, locus);
    }

    #[test]
    fn an_attested_computation_carries_executor_and_attester_separately() {
        let ac = AttestedComputation {
            runtime: "oxigraph/0.4".to_owned(),
            parameters: BTreeMap::new(),
            computation: "ASK { ?s a owl:Class }".to_owned(),
            executor: Executor {
                resource: "process:vault/1.0".to_owned(),
                receipt: Some("run-17".to_owned()),
            },
            attester: Attester {
                resource: "human:npub1abc".to_owned(),
            },
        };
        let json = serde_json::to_value(&ac).expect("serialise");
        assert_eq!(json["executor"]["receipt"], "run-17");
        assert_eq!(json["attester"]["resource"], "human:npub1abc");
    }
}
